### ISSUE TITLE
`require': cannot load such file -- html/table (LoadError)

### ISSUE THREAD

**Issue by hahwul** [hahwul/droid-hunter#1]
# > ruby dhunter.rb

/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- html/table (LoadError)
    from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /home/hahwul/HAHWUL/MyTool/droid-hunter/src/generate_report.rb:1:in `<top (required)>'
    from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from dhunter.rb:3:in`<main>'

**Comment by hahwul** [comment]
#> gem install html-table
