### ISSUE TITLE
ERROR: no dump file specified

### ISSUE THREAD

**Issue by its-arun** [hahwul/droid-hunter#9]
[START] Analysis to 
[INFO] Start Basic Analysis
dhunter.rb:75:in `mkdir': no implicit conversion of nil into String (TypeError)
	from dhunter.rb:75:in `make_work'
	from dhunter.rb:169:in `<main>'

**Comment by naiksrinu** [comment]
**whats the solution for the issue?**

root@CyberFit:/opt/droid-hunter# ruby dhunter.rb -a  /home/test999.apk
      .---.        .-----------
     /     \  __  /    ------
    / /     \(  )/    -----     ╔╦╗╦═╗╔═╗╦╔╦╗   ╦ ╦╦ ╦╔╗╔╔╦╗╔═╗╦═╗
   //////   ' \/ `   ---         ║║╠╦╝║ ║║ ║║───╠═╣║ ║║║║ ║ ║╣ ╠╦╝
  //// / // :    : ---          ═╩╝╩╚═╚═╝╩═╩╝   ╩ ╩╚═╝╝╚╝ ╩ ╚═╝╩╚═
 // /   /  /`    '--                         By HaHwul
//          //..\\                         www.hahwul.com
       ====UU====UU====         https://github.com/hahwul/droid-hunter
           '//||\\`
             ''``
sh: 1: Syntax error: "(" unexpected
[START] Analysis to 
[INFO] Start Basic Analysis
_dhunter.rb:76:in `mkdir': no implicit conversion of nil into String (TypeError)
	from dhunter.rb:76:in `make_work'
	from dhunter.rb:178:in `<main>'_
root@CyberFit:/opt/droid-hunter#
